language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
before_install:
  - npm install -g codecov
env:
  global: CODECOV_TOKEN=bd4c116b-793d-4afd-a5e6-a67d35552bdb
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
script:
  - npm test
  - npm run test:coverage
