language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  global: CODECOV_TOKEN=bd4c116b-793d-4afd-a5e6-a67d35552bdb
script:
  - npm test
  - npm run test:coverage
  - npm run build
